# Generated by Django 4.2.5 on 2023-10-19 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0004_auth_alter_book_rating_alter_book_slug_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auth',
            new_name='Author',
        ),
    ]
